insert into EdecCategory values (1,'carne lactate mezeluri');
insert into EdecCategory values (2,'brutarie');
insert into EdecCategory values (3,'bacanie');
insert into EdecCategory values (4,'bautura si tutun');
insert into EdecCategory values (5,'fructe si legume');
insert into EdecCategory values (6,'curatenie si intretinere');
insert into EdecCategory values (7,'igiena si infrumusetare');
insert into EdecCategory values (8,'casa, auto si hobby');
insert into EdecCategory values (9,'univers bebe si jucarii');
insert into EdecCategory values (10,'tv, electrocasnice si electronice');
insert into EdecCategory values (11,'IT, comunicatii si foto');